FROM registry.ci.openshift.org/ocp/builder:rhel-9-golang-1.25-openshift-4.22 AS builder
WORKDIR /go/src/github.com/aws/aws-node-termination-handler
COPY . .
RUN CGO_ENABLED=0 go build -mod=vendor -tags nthlinux -ldflags="-s -w" -o /go/bin/node-termination-handler ./cmd/node-termination-handler.go

FROM registry.ci.openshift.org/ocp/4.22:base-rhel9
COPY --from=builder /go/bin/node-termination-handler /usr/bin/
LABEL io.openshift.release.operator=true
ENTRYPOINT ["/usr/bin/node-termination-handler"]
